workspace(name = "app")
load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')

git_repository(
    name = "mxebzl",
    remote = "https://github.com/skykying/mingw-bzl.git",
    tag = "2020_10_06_rc1",  # Adjust as needed
)

load("@mxebzl//compiler:repository.bzl", "mxe_compiler")
mxe_compiler(
    deps = [
        "compiler",
        # "SDL2",
        # "sqlite",
        # etc...
    ],
)