workspace(name = "app")
load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')

git_repository(
    name = "mxebzl",
    remote = "https://github.com/skykying/mingw-bzl.git",
    tag = "20181103_RC02",  # Adjust as needed
)

load("@mxebzl//tools:repository.bzl", "mxe_compilers")
mxe_compilers(
    deps = [
        "compiler",
        # "SDL2",
        # "sqlite",
        # etc...
    ],
)